"""Data models for the postgres_agent component."""

from __future__ import annotations

from pydantic import BaseModel, Field

# Maximum characters kept per sample-row cell when rendering schema text.
_SAMPLE_CELL_CHARS = 80


class GeneratedSQL(BaseModel):
    """A SQL query generated by the LLM from a natural-language question."""

    sql: str = Field(
        ...,
        description="A single read-only PostgreSQL SELECT (a leading WITH is allowed).",
    )
    reasoning: str = Field(
        ...,
        max_length=500,
        description="Brief explanation of how the query answers the question.",
    )


class ColumnInfo(BaseModel):
    """A single column of a database table."""

    name: str
    data_type: str
    nullable: bool = True
    is_primary_key: bool = False
    references: str | None = Field(
        default=None,
        description="'table.column' when this column is a foreign key.",
    )


class TableInfo(BaseModel):
    """A single database table, its columns, and optional sample rows."""

    name: str
    columns: list[ColumnInfo] = Field(default_factory=list)
    sample_rows: list[dict] = Field(default_factory=list)


class SchemaInfo(BaseModel):
    """The introspected relational schema the agent reasons over."""

    schema_name: str
    tables: list[TableInfo] = Field(default_factory=list)

    def to_prompt_text(self) -> str:
        """Render a compact, LLM-friendly description of the schema."""
        if not self.tables:
            return f"(schema '{self.schema_name}' contains no tables)"
        blocks: list[str] = []
        for table in self.tables:
            lines = [f"TABLE {table.name} ("]
            for col in table.columns:
                parts = [f"  {col.name} {col.data_type}"]
                if col.is_primary_key:
                    parts.append("PRIMARY KEY")
                if not col.nullable:
                    parts.append("NOT NULL")
                if col.references:
                    parts.append(f"REFERENCES {col.references}")
                lines.append(" ".join(parts))
            lines.append(")")
            block = "\n".join(lines)
            if table.sample_rows:
                block += "\nsample rows:"
                for row in table.sample_rows:
                    block += f"\n  {_format_sample_row(row)}"
            blocks.append(block)
        return "\n\n".join(blocks)


def _format_sample_row(row: dict) -> str:
    """Render one sample row as a compact, length-capped string."""
    cells = []
    for key, value in row.items():
        text = "NULL" if value is None else str(value)
        if len(text) > _SAMPLE_CELL_CHARS:
            text = text[:_SAMPLE_CELL_CHARS] + "…"
        cells.append(f"{key}={text}")
    return ", ".join(cells)


class QueryResult(BaseModel):
    """Outcome of the agentic text-to-SQL loop for one question."""

    question: str
    sql: str | None = None
    reasoning: str | None = None
    rows: list[dict] = Field(default_factory=list)
    row_count: int = 0
    attempts: int = 0
    succeeded: bool = False
    error: str | None = None


class AnswerResult(BaseModel):
    """A natural-language answer plus the QueryResult it was derived from."""

    question: str
    answer: str
    query_result: QueryResult
